#!/usr/bin/env python3
"""Generate device Lloyd-Max codebook constants for TurboQuant."""

import json
from pathlib import Path


SUPPORTED_DIMS = (256, 512, 1024, 2048)
SUPPORTED_BITS = (2, 3, 4, 5, 6, 7, 8)


def format_float(value: float) -> str:
    text = f"{value:.10g}"
    if "e" not in text and "." not in text:
        text += ".0"
    return f"{text}f"


def emit_array(name, values, width=8):
    lines = [f"__device__ __constant__ float {name}[{len(values)}] = {{"]
    for i in range(0, len(values), width):
        chunk = ", ".join(format_float(v) for v in values[i : i + width])
        suffix = "," if i + width < len(values) else ""
        lines.append(f"    {chunk}{suffix}")
    lines.append("};")
    return lines


def load_codebook(codebook_dir, dim, bits):
    path = codebook_dir / f"codebook_d{dim}_b{bits}.json"
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if int(data["d"]) != dim or int(data["bits"]) != bits:
        raise ValueError(f"{path} metadata does not match filename")
    centroids = [float(x) for x in data["centroids"]]
    boundaries = [float(x) for x in data["boundaries"]]
    levels = 1 << bits
    if len(centroids) != levels:
        raise ValueError(f"{path} has {len(centroids)} centroids, expected {levels}")
    if len(boundaries) != levels + 1:
        raise ValueError(f"{path} has {len(boundaries)} boundaries, expected {levels + 1}")
    return centroids, boundaries


def main() -> None:
    root = Path(__file__).resolve().parent
    codebook_dir = root / "codebook"
    out_path = root / "tq_codebooks_generated.hpp"

    lines = [
        "#pragma once",
        "",
        "// Generated by turboquant/generate_tq_codebooks_header.py.",
        "// Do not edit this file by hand.",
        "",
        "namespace turboquant {",
        "namespace {",
        "",
    ]

    for dim in SUPPORTED_DIMS:
        for bits in SUPPORTED_BITS:
            centroids, boundaries = load_codebook(codebook_dir, dim, bits)
            lines.extend(emit_array(f"d{dim}_b{bits}_centroids", centroids))
            lines.extend(emit_array(f"d{dim}_b{bits}_boundaries", boundaries))
            lines.append("")

    lines.extend(
        [
            "struct TQDeviceCodebook {",
            "    const float* centroids;",
            "    const float* boundaries;",
            "    int levels;",
            "};",
            "",
            "__device__ __forceinline__",
            "TQDeviceCodebook get_tq_codebook_device(int dim, int bits) {",
            "    switch (dim) {",
        ]
    )

    for dim in SUPPORTED_DIMS:
        lines.append(f"        case {dim}:")
        lines.append("            switch (bits) {")
        for bits in SUPPORTED_BITS:
            levels = 1 << bits
            lines.append(
                f"                case {bits}: return "
                f"{{d{dim}_b{bits}_centroids, d{dim}_b{bits}_boundaries, {levels}}};"
            )
        lines.append("                default: return {nullptr, nullptr, 0};")
        lines.append("            }")

    lines.extend(
        [
            "        default: return {nullptr, nullptr, 0};",
            "    }",
            "}",
            "",
            "}  // namespace",
            "}  // namespace turboquant",
            "",
        ]
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
