#!/usr/bin/env python3
"""Sanity-check an OISST raw float32 matrix with exact and randomized SVD.

The input file is expected to be raw row-major float32 with shape (m, n).
Exact SVD is only run on a smaller leading submatrix.  Full randomized SVD can
be run blockwise with NumPy so the whole matrix does not need to be copied into
RAM at once.
"""

import argparse
import os
import sys

try:
    import numpy as np
except ImportError as exc:
    raise SystemExit(
        "This checker requires numpy. On this Python 3.6 environment, try:\n"
        "  python3 -m pip install --user 'numpy<1.20'\n"
        "or run this script inside the same scientific Python environment used to prepare OISST."
    ) from exc


def reconstruction_error_from_singular_values(s, fro2, k):
    captured = float(np.sum(s[:k] * s[:k]))
    err2 = max(float(fro2) - captured, 0.0)
    return float(np.sqrt(err2 / float(fro2)))


def pct(x):
    return f"{x * 100.0:.4f}%"


def summarize(xs):
    arr = np.asarray(xs, dtype=np.float64)
    return {
        "mean": float(arr.mean()),
        "min": float(arr.min()),
        "stddev": float(arr.std(ddof=0)),
    }


def parse_work_dtype(name):
    if name == "float32":
        return np.float32
    if name == "float64":
        return np.float64
    raise ValueError(f"unsupported work dtype: {name}")


def scan_matrix_stats(A, block_rows):
    m, n = A.shape
    total_count = m * n
    total_sum = 0.0
    total_sumsq = 0.0
    max_abs = 0.0
    has_nan = False
    has_inf = False

    row_mean_sum = 0.0
    row_mean_sumsq = 0.0
    max_abs_row_mean = 0.0

    for start in range(0, m, block_rows):
        stop = min(start + block_rows, m)
        block = np.asarray(A[start:stop, :], dtype=np.float64)

        has_nan = has_nan or bool(np.isnan(block).any())
        has_inf = has_inf or bool(np.isinf(block).any())

        total_sum += float(np.sum(block))
        total_sumsq += float(np.sum(block * block))
        max_abs = max(max_abs, float(np.max(np.abs(block))))

        row_means = block.mean(axis=1)
        row_mean_sum += float(np.sum(row_means))
        row_mean_sumsq += float(np.sum(row_means * row_means))
        max_abs_row_mean = max(max_abs_row_mean, float(np.max(np.abs(row_means))))

    mean = total_sum / float(total_count)
    variance = max(total_sumsq / float(total_count) - mean * mean, 0.0)
    row_mean_mean = row_mean_sum / float(m)
    row_mean_rms = np.sqrt(row_mean_sumsq / float(m))

    return {
        "has_nan": has_nan,
        "has_inf": has_inf,
        "mean": mean,
        "std": float(np.sqrt(variance)),
        "fro2": total_sumsq,
        "mean_abs_proxy": None,
        "max_abs": max_abs,
        "row_mean_mean": row_mean_mean,
        "row_mean_rms": float(row_mean_rms),
        "max_abs_row_mean": max_abs_row_mean,
    }


def block_a_times_x(A, X, block_rows, dtype):
    m, _ = A.shape
    Y = np.empty((m, X.shape[1]), dtype=dtype)
    for start in range(0, m, block_rows):
        stop = min(start + block_rows, m)
        A_block = np.asarray(A[start:stop, :], dtype=dtype)
        Y[start:stop, :] = A_block @ X
    return Y


def block_at_times_x(A, X, block_rows, dtype):
    m, n = A.shape
    Z = np.zeros((n, X.shape[1]), dtype=dtype)
    for start in range(0, m, block_rows):
        stop = min(start + block_rows, m)
        A_block = np.asarray(A[start:stop, :], dtype=dtype)
        Z += A_block.T @ X[start:stop, :]
    return Z


def block_qt_times_a(A, Q, block_rows, dtype):
    m, n = A.shape
    B = np.zeros((Q.shape[1], n), dtype=dtype)
    for start in range(0, m, block_rows):
        stop = min(start + block_rows, m)
        A_block = np.asarray(A[start:stop, :], dtype=dtype)
        B += Q[start:stop, :].T @ A_block
    return B


def randomized_svd_numpy(A, k, oversample, n_iter, seed, block_rows, dtype):
    """Blockwise randomized SVD using NumPy primitives.

    This computes singular values of B = Q^T A, where Q is generated by the
    standard randomized range finder.  It mirrors the same error proxy used by
    the CUDA implementation: ||A - QQ^T A||_F estimated from singular values of B.
    """

    m, n = A.shape
    ell = min(k + oversample, m, n)
    rng = np.random.RandomState(seed)
    Omega = rng.standard_normal((n, ell)).astype(dtype, copy=False)

    Y = block_a_times_x(A, Omega, block_rows, dtype)
    Q, _ = np.linalg.qr(Y, mode="reduced")
    Q = Q.astype(dtype, copy=False)

    for _ in range(n_iter):
        Z = block_at_times_x(A, Q, block_rows, dtype)
        Y = block_a_times_x(A, Z, block_rows, dtype)
        Q, _ = np.linalg.qr(Y, mode="reduced")
        Q = Q.astype(dtype, copy=False)

    B = block_qt_times_a(A, Q, block_rows, dtype)
    return np.linalg.svd(B, compute_uv=False)


def randomized_svd_sklearn(A, k, oversample, n_iter, seed, dtype):
    from sklearn.utils.extmath import randomized_svd

    A_full = np.asarray(A, dtype=dtype)
    _, s, _ = randomized_svd(
        A_full,
        n_components=k,
        n_oversamples=oversample,
        n_iter=n_iter,
        random_state=seed,
    )
    return s


def main():
    parser = argparse.ArgumentParser(
        description="Validate an OISST raw .f32 matrix with NumPy SVD checks.",
    )
    parser.add_argument("--file", required=True, help="Raw row-major float32 matrix file.")
    parser.add_argument("--m", type=int, required=True, help="Number of rows.")
    parser.add_argument("--n", type=int, required=True, help="Number of columns.")
    parser.add_argument("--k", type=int, default=250, help="Target rank.")
    parser.add_argument("--sample-rows", type=int, default=4096, help="Rows for exact-SVD submatrix check.")
    parser.add_argument("--sample-cols", type=int, default=2048, help="Columns for exact-SVD submatrix check.")
    parser.add_argument("--full-randomized", action="store_true", help="Run a full randomized SVD sanity check.")
    parser.add_argument("--randomized-backend", choices=("numpy", "sklearn"), default="numpy")
    parser.add_argument("--oversample", type=int, default=16)
    parser.add_argument("--n-iter", type=int, default=1)
    parser.add_argument("--seed", type=int, default=1234)
    parser.add_argument(
        "--repeat",
        type=int,
        default=50,
        help="Number of randomized SVD trials. Seeds follow the CUDA accuracy phase: seed+1, seed+2, ...",
    )
    parser.add_argument("--block-rows", type=int, default=1024)
    parser.add_argument("--work-dtype", choices=("float32", "float64"), default="float64")
    args = parser.parse_args()

    expected = args.m * args.n * np.dtype(np.float32).itemsize
    actual = os.path.getsize(args.file)
    print(f"file size: {actual} bytes")
    print(f"expected : {expected} bytes")
    if actual != expected:
        raise SystemExit("File size does not match m*n*sizeof(float).")

    A = np.memmap(args.file, dtype=np.float32, mode="r", shape=(args.m, args.n), order="C")
    print("shape:", A.shape)
    print("dtype:", A.dtype)

    stats = scan_matrix_stats(A, args.block_rows)
    print("has NaN:", stats["has_nan"])
    print("has Inf:", stats["has_inf"])
    print("mean:", stats["mean"])
    print("std:", stats["std"])
    print("frobenius norm:", float(np.sqrt(stats["fro2"])))
    print("max abs:", stats["max_abs"])
    print("mean(row mean):", stats["row_mean_mean"])
    print("row mean RMS:", stats["row_mean_rms"])
    print("max abs(row mean):", stats["max_abs_row_mean"])

    sr = min(args.sample_rows, args.m)
    sc = min(args.sample_cols, args.n)
    k_small = min(args.k, sr, sc)

    dtype = parse_work_dtype(args.work_dtype)

    print(f"\n[Exact SVD sanity check on submatrix {sr} x {sc}]")
    print(f"exact SVD work dtype: {args.work_dtype}")
    A_small = np.asarray(A[:sr, :sc], dtype=dtype)
    fro2_small = float(np.sum(A_small * A_small))
    s_small = np.linalg.svd(A_small, compute_uv=False)
    err_small = reconstruction_error_from_singular_values(s_small, fro2_small, k_small)
    print(f"submatrix k={k_small} reconstruction error: {pct(err_small)}")
    print(f"submatrix captured energy: {pct(1.0 - err_small * err_small)}")
    print("top singular values:", " ".join(f"{x:.6g}" for x in s_small[: min(10, len(s_small))]))

    if args.full_randomized:
        print(f"\n[Full randomized SVD check on {args.m} x {args.n}]")
        print(
            "backend:",
            args.randomized_backend,
            f"k={args.k}",
            f"oversample={args.oversample}",
            f"n_iter={args.n_iter}",
            f"seed={args.seed}",
            f"work_dtype={args.work_dtype}",
        )

        errors = []
        first_s = None
        for trial in range(args.repeat):
            # CUDA v4 uses repeat_seed = seed + trial and Omega seed = repeat_seed + 1.
            trial_seed = args.seed + trial + 1
            if args.randomized_backend == "numpy":
                s = randomized_svd_numpy(
                    A,
                    args.k,
                    args.oversample,
                    args.n_iter,
                    trial_seed,
                    args.block_rows,
                    dtype,
                )
            else:
                s = randomized_svd_sklearn(A, args.k, args.oversample, args.n_iter, trial_seed, dtype)

            if first_s is None:
                first_s = s
            err = reconstruction_error_from_singular_values(s, stats["fro2"], args.k)
            errors.append(err)
            if args.repeat > 1:
                print(f"trial {trial + 1}/{args.repeat} seed={trial_seed} reconstruction error: {pct(err)}")

        summary = summarize(errors)
        print(f"full randomized SVD k={args.k} reconstruction error: {pct(summary['mean'])}")
        print(f"full randomized SVD min reconstruction error: {pct(summary['min'])}")
        print(f"full randomized SVD stddev: {pct(summary['stddev'])}")
        print(f"full randomized SVD captured energy: {pct(1.0 - summary['mean'] * summary['mean'])}")
        print("top randomized singular values:", " ".join(f"{x:.6g}" for x in first_s[: min(10, len(first_s))]))


if __name__ == "__main__":
    sys.exit(main())
